import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google"; // Eliminado para compatibilidad con Next.js 14
import "./globals.css";
import ConditionalLayoutWrapper from '@/components/ConditionalLayoutWrapper'; // Importar el nuevo componente
import { ThemeProvider } from '@/components/ThemeProvider';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Inventario ATT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen`}
      >
        <ThemeProvider>
          <ConditionalLayoutWrapper>
            {children}
          </ConditionalLayoutWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
